import type { Metadata } from "next";
import "./globals.css";

import { HeroUIProvider } from "@heroui/react";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { LanguageProvider } from "./LanguageContext";

import NavigationBar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
          <HeroUIProvider>
            <NextThemesProvider attribute="class" defaultTheme="light">
              <NavigationBar />
              {children}
              <Footer />
            </NextThemesProvider>
          </HeroUIProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
